import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { NextAuthProvider } from '@/components/Providers'
import { Poppins } from 'next/font/google';
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export  default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  const session = await getServerSession(authOptions)
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className={inter.className}>

        <NextAuthProvider>

          <div className='relative'>

            <Navbar session = {session}/>
            <div className='mt-16'>

              {children}
            </div>
          </div>
        </NextAuthProvider>



      </body>

    </html>
  )
}
